leg:
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  jumper_position_controller:
    type: effort_controllers/JointPositionController
    joint: jumper
    pid: { p: 50, d: 2, i: 0 }
  hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: hip_joint
      pid: {p: 150, d: 0.01, i: 0 }
  thigh_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_joint
    pid: { p: 50, d: 0.01, i: 0 }
  calf_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: calf_joint
    pid: { p: 20, d: 0.001, i: 0 }