leg:
  joint_states_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

  hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: hip_joint
      pid: {p: 200, d: 1, i: 1 }
  thigh_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: thigh_joint
    pid: { p: 200, d: 1, i: 1 }
  calf_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: calf_joint
    pid: { p: 140, d: 0.01, i: 0.01 }